### ISSUE TITLE
Needs to send the 'client_started' rpc to enable syntax highlighting

### ISSUE THREAD

**Issue by patrickisgreene** [little-dude/xi-tui#47]
I will have some free time later in the week, i have a local fork with this working with [xdg](https://github.com/whitequark/rust-xdg), if your ok with the added dependency i can create a PR.

**Comment by ryukinix** [comment]
How you did that? I have the same problem and I want a fix for it.

**Comment by ryukinix** [comment]
@bytebuddha I tried your own fork, but syntax highlight is not working yet... I should do something more? I followed the instructions wrote on the README.md of this repository, installed xi-core and the syntax highlight syntect plugin as well.

**Comment by patrickisgreene** [comment]
@ryukinix  it should be working but i haven't tried in like a month. do you have a config directory in $XDG_CONFIG_HOME(~/.config/xi) witch contains the syntect plugin?

EDIT: didn't mean to close it

**Comment by ryukinix** [comment]
@bytebuddha I fixed after saw that the install instructions was pointing to do a `cargo install` instead `make install`, this fix the problem.

**Comment by jorge-jbs** [comment]
I have installed the syntect plugin with `make install` and I don't get syntax highlighting. My plugin folder looks like this:

```
/home/jorge/.config/xi/plugins/syntect
├── bin
│   └── xi-syntect-plugin
└── manifest.toml
```

Is there anything I am doing wrong? Thanks for the help :)

**Comment by ryukinix** [comment]
Yes, this issue is not fixed yet.

There is some forks with have this fixed:
- https://github.com/bytebuddha/xi-tui
- https://github.com/DestructHub/xim

**Comment by little-dude** [comment]
@bytebuddha @ryukinix if you're actively maintaining a fork, should I update the README and link to your project instead? I have not had much time to work on `xi-tui` lastly. Or I can make you admin of this repo if you prefer, or transfer ownership to a xi-tui organization. Let me know what you prefer.

**Comment by little-dude** [comment]
An organization might make sense, since there's also the `xrl` repo.

**Comment by patrickisgreene** [comment]
I think an xrl organization would be best(with xi-tui as a repo), it would be easier to share work between us and as Xi grows we could add more crates like xrl that would be useful to many different frontend's.

**Comment by ryukinix** [comment]
I vote for the organization

**Comment by patrickisgreene** [comment]
@ryukinix Just curious would you give any thought into merging xim under said organization and we can all begin working together on thing's?

**Comment by ryukinix** [comment]
I'm a completely ok with that. When the organization will be made, I may transfer the ownership of xim to this organization, let's say DestructHub/xim -> xrl/xim. I don't have sure yet if the xrl is the better name for this organization, btw -- but I don't have any suggestion for now too.

Since we three, me, @bytebuddha e @little-dude, are doing stuff about xi editor written in Rust would be nice synchronize the development. Another guy that should be added in development is my partner in the xim development @leonardohn.

Xim has a goal maybe a little different of xi-tui. Currently we don't want to create another vim, but a new thing as experiment for terminal editor interfaces, focused in minimalism. Since @little-dude made a great work with xrl protocol and xi-tui based, I decided to start with the fork.

**Comment by patrickisgreene** [comment]
That's cool I'd like to fool around with it! I personally would like xi-tui to be more vim like. It just seem's necessary to have a vim like xi-editor, but that's just personal preference. None the less I'd like to contribute to all xrl, xi-tui and xim and an organization would simplify that.

I also am not big on the name xrl maybe xi-tokio?

**Comment by ryukinix** [comment]
> I personally would like xi-tui to be more vim like. It just seem's necessary to have a vim like xi-editor, but that's just personal preference

I agree with that, but since I think that xi-tui maybe will achieve that goal, I'm taking an other side. 

> I also am not big on the name xrl maybe xi-tokio?

:thinking:  seems better

**Comment by patrickisgreene** [comment]
I agree, it's about time for something better than vim/emacs.

Other names i've thought about before, though i'm not sure if they should follow xi convention or not.
    - xi-engine
    - xi-frontend

**Comment by ryukinix** [comment]
`xi-frontend` seems explicit what we do, but maybe is too broad? :thinking: 

But I'm ok with xi-frontend. `xi-engine` can be misleading since engine can be anything and someone can be confused with the xi-core stuff.

**Comment by little-dude** [comment]
Hey guys. I'm dealing with some personal issues so will be offline for the coming week. You can go ahead and create the organization, I'll try to transfer me repos if I find some time to login this week.

**Comment by patrickisgreene** [comment]
I don't think it would be to broad that same organization could be used to host other common front end library's. I'd eventually like to extract the serde code in xrl to an xi-serde crate so any front end can use them without bringing in the tokio/futures dependencyies. but name's are unimportant to me. @ryukinix  Do you want to make the organization whenever you find a name you like and time to do it?

**Comment by ryukinix** [comment]
I can create the organization without problems. I'll get `xi-frontend` since is the best name until now.

**Comment by cmyr** [comment]
Fwiw there's definitely interest in possibly using xrl in xi-core at some point, but we'll get there when we get there.

**Comment by cmyr** [comment]
And while everyone's bike-shedding, another possible name for an org might be `xi-term`?

**Comment by ryukinix** [comment]
:thinking: I think xi-term is a new term (terminology) that close the domain too much about terminals. I think xi-frontend is in someway better. For now we'll have that repositories:

- xim (fork of xi-tui but keeping minimalism as priority)
- xrl (the xi RPC protocol based on tokio)
- repos of bytebuddha that I don't know what is

But bytebuddha I think have some graphical interface as xi client, so I prefer don't close the domain too much as `term` stuff.

BTW, I already created the org at www.github.com/xi-frontend

**Comment by ryukinix** [comment]
@bytebuddha @little-dude you are owners of the org too, please, accept the invitation.

**Comment by patrickisgreene** [comment]
Awesome!

> And while everyone's bike-shedding, another possible name for an org might be xi-term?

I had intentionally left that out because i'd also like @little-dude to consider changing xi-tui name to xi-term, during the move.

**Comment by patrickisgreene** [comment]
> repos of bytebuddha that I don't know what is

I know It's probably confusing looking at my xi related repo's so just so we are clear my personal projects are:
 - **Zen** is a front end based on webrender and limn but as I've experimented with it in private repos I've pretty much decided webrender, and especially limn just aren't ready for it yet so is on hold.
- **xi-core-py** This one was just my exparement creating python modules with the pyo3 library
- **xi_connection** Basically xrl, i abandoned work on it once little-dude published xrl

I don't plan on adding any of these under the org(accept maybe Zen way in the future). And i would propose any crates I plan to add to all owners of xi-frontend before adding them.

**Comment by ryukinix** [comment]
Which repos do you have interest to migrate to our organization?

**Comment by patrickisgreene** [comment]
just a private repo called xi-serde, it's hard to find time to work on things at the moment. So i probably can't add it for a few week's

**Comment by little-dude** [comment]
Hey :) I transfered `xrl`. I could not transfer `xi-tui` because there's already a fork of it in the org (`xim`). If we want to transfer xi-tui we'll have to remove xim first. I'm ok renaming `xi-tui` to `xi-term`.

**Comment by ryukinix** [comment]
Hmm... this is a problem. Because you'll lost all the issues and stuff. I can as well do the same, delete the xim repo. I'll try do a type of migration, wait a little.

**Comment by ryukinix** [comment]
@little-dude done, now you can transfer it.

**Comment by little-dude** [comment]
Done. I'll be offline for a while now.

**Comment by patrickisgreene** [comment]
I think everything is just about flushed out here closing!
